version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - taster.env
    volumes:
      - ./config:/inst
      - ./www/docs:/inst/www/docs
  db:
     image: postgres
     ports:
       - "5432:5432"
     env_file:
       - taster.env
     hostname: sprague-ubuntu
       