default:
  golem_name: tastermonial
  golem_version: 0.0.1.0001
  app_prod: no
  dataconnection:
    driver: !expr RPostgres::Postgres()
    host: !expr Sys.getenv("TASTER_HOST")
    user: !expr Sys.getenv("TASTER_USER")
    password: !expr Sys.getenv("TASTER_PASSWORD")
    port: !expr Sys.getenv("TASTER_PORT")
    dbname: !expr Sys.getenv("TASTER_DBNAME")
    glucose_table: 'glucose_records'
local:
  golem_name: tastermonial
  golem_version: 0.0.1.0001
  app_prod: no
  dataconnection:
    driver: !expr RPostgres::Postgres()
    host: !expr Sys.getenv("LOCAL_HOST")
    user: !expr Sys.getenv("LOCAL_USER")
    password: !expr Sys.getenv("LOCAL_PASSWORD")
    port: !expr Sys.getenv("LOCAL_PORT")
    dbname: !expr Sys.getenv("LOCAL_DBNAME")
    glucose_table: 'glucose_records'
production:
  app_prod: yes
dev:
  golem_wd: /Users/sprague/dev/psi/taster
